### ISSUE TITLE
[feature] 커뮤니티 UI 수정

### ISSUE THREAD

**Issue by leejin-rho** [Briefing-for-construction-workers/frontend#43]
### 📌 구현 기능

- 커뮤니티 페이지 수정

### 🛠 작업 내용

- [ ] 커뮤니티 페이지 바뀐 UI 수정

### 💬 기타 사항

-

**Comment by aqua-universalis** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2024-07-27T15:20:13
          
          
            * 메일 제목 : 
Re: [Briefing-for-construction-workers/frontend] [feature] 커뮤니티 UI 수정 (Issue #43)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.
