### ISSUE TITLE
[feature] AddButtonView 수정

### ISSUE THREAD

**Issue by qkrtnqja97** [Briefing-for-construction-workers/frontend#51]
📌 구현 기능

> AddButtonView 수정

🛠 작업 내용

- 이전: AddButtonView 컴포넌트 사용이 Home스크린의 '공사추가하기' 버튼에 국한됨.
   -> 현재: AddButonView 컴포넌트 호출 시 value 값으로 버튼 안의 문자열 설정가능 / 문자열에 따른 onPress 함수 설정 가능
- 구인구직 버튼 클릭 시 햄버거 버튼을 위한 AddSubButton 생성 (@/globals/styles/GlobalStyle)

 커뮤니티 페이지 바뀐 UI 수정
💬 기타 사항
- AddButtonView 컴포넌트 호출 방식 변경
  이전: <AddButtonView navigation={navigation} />
  현재: <AddButtonView navigation={navigation} value={"버튼안의 문자열"} />

**Comment by aqua-universalis** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2024-07-25T01:19:12
          
          
            * 메일 제목 : 
[E-5-KAIST-Team04/frontend] [feature] AddButtonView 수정 (Issue #51)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

**Comment by qkrtnqja97** [comment]
현재 구현 완료

**Comment by aqua-universalis** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2024-07-25T01:19:59
          
          
            * 메일 제목 : 
Re: [E-5-KAIST-Team04/frontend] [feature] AddButtonView 수정 (Issue #51)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

**Comment by aqua-universalis** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2024-08-02T18:25:31
          
          
            * 메일 제목 : 
Re: [Briefing-for-construction-workers/frontend] [feature] AddButtonView 수정 (Issue #51)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.
